<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controllers\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AquaAirAlert.Application\AquaAirAlert.Application.csproj" />
      <ProjectReference Include="..\AquaAirAlert.Communication\AquaAirAlert.Communication.csproj" />
      <ProjectReference Include="..\AquaAirAlert.Exception\AquaAirAlert.Exception.csproj" />
      <ProjectReference Include="..\AquaAirAlert.Infrastructure\AquaAirAlert.Infrastructure.csproj" />
    </ItemGroup>

</Project>
